spring:
  application:
    name: Eatsfine
  profiles:
    active: local

cloud:
  aws:
    region: ap-northeast-2
    s3:
      bucket: eatsfine-images
      base-url: https://eatsfine-images.s3.ap-northeast-2.amazonaws.com