name: Deploy
on:
  push:
    branches:
      - develop
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 체크 아웃
        uses: actions/checkout@v4

      - name: Java 21 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle 캐싱
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os}}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os}}-gradle-

      - name: gradlew 파일 실행권한 부여
        run: chmod +x gradlew
        shell: bash

      - name: 프로젝트 빌드
        run: |
          ./gradlew build

      - name: DockerHub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: 도커 이미지 빌드
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/eatsfine-be .

      - name: 도커 이미지 푸시
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/eatsfine-be:latest

      - name: EC2 배포
        run: |
          
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/eatsfine-ec2-key.pem
          chmod 600 ~/.ssh/eatsfine-ec2-key.pem
          
          ssh -o StrictHostKeyChecking=no \
            -i <(echo "${{ secrets.EC2_SSH_KEY }}") \
            ${{ secrets.EC2_USERNAME }}@${{ secrets.LIVE_SERVER_IP }} << 'EOF'
          
            set -e
            cd /home/ec2-user/deploy
          
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/eatsfine-be:latest
          
            docker compose down
            docker compose up -d
          
            docker ps
          EOF